image: node:7.8.0

stages:
  - test

before_script:
  - apt-get update -y
  - npm install

cache:
  paths:
    - node_modules/
test:
  stage: test
  script:
    - yarn test

build:
  stage: build
  script:
    - yarn build